[terminal]
shell = { program = "wsl.exe", args = ["-d", "Ubuntu-22.04", "--cd", "~"] }

[window]
startup_mode = "windowed"

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "Consolas", style = "Regular" }
size = 11.0
